### ISSUE TITLE
Merge with chisui/bsa?

### ISSUE THREAD

**Issue by chisui** [printfn/bsa#2]
I'm also working actively on a [bsa lib/cli-tool in rust](https://github.com/chisui/bsa). It currently fully supports v103 to v105 and extraction for v001(Morriwind). Support for `.ba2` is also planed. Would you be interested in merging these two projects?

**Comment by printfn** [comment]
Sure! I've tried adding you as an owner on crates.io, so hopefully that worked?
Feel free to just publish your crate as "bsa", since it already seems to have quite a few more features than mine.

**Comment by chisui** [comment]
Cool, thank you.
